dist: bionic

language: python

python:
  #- "3.7"
  - "3.8.5"

cache:
  pip: true
  directories:
    - $HOME/db/
    #- ${TRAVIS_BUILD_DIR}/scripts/output/

git:
  depth: 3

env:
  global:
    - GIT_NAME: Spirillen
    - GIT_EMAIL: "44526987+spirillen@users.noreply.github.com"
    - TRAVIS_REPO_SLUG: ${TRAVIS_REPO_SLUG} #dns-test/rpz.mypdns.cloud
    - TZ: UTC
    - SCRIPT_SOURCE_URI: 'https://raw.githubusercontent.com/dns-test/script-hub/master'
    - PYTHON_VERSION: 3.8.5
    - Pyfunceble_version: 'PyFunceble@raw2sqlalchemy'
    - PYFUNCEBLE_CONFIG_DIR: "${TRAVIS_BUILD_DIR}/scripts/"
    - PYFUNCEBLE_OUTPUT_LOCATION: "${TRAVIS_BUILD_DIR}/scripts/"
    - PYFUNCEBLE_AUTO_CONFIGURATION: yes
    - PYFUNCEBLE_DB_CHARSET="${DB_CHARSET}"
    - PYFUNCEBLE_DB_HOST="${DB_HOST}"
    - PYFUNCEBLE_DB_NAME="${DB_NAME}"
    - PYFUNCEBLE_DB_USERNAME="${DB_USERNAME}"
    - PYFUNCEBLE_DB_PASSWORD="${DB_PASSWORD}"
    - PYFUNCEBLE_DB_PORT="${DB_PORT}"

addons:
  mariadb: '10.5'
  apt:
    packages:
      - dos2unix
      - msttcorefonts
      - lsof
      #- pdns-recursor
    update: true
  
install:
  - pip3 install --upgrade pip
  #- pip3 install --no-cache-dir -U "git+https://github.com/funilrys/${Pyfunceble_version}"
  - pip3 install --no-cache-dir -U pyfunceble-dev
  #- pip3 install ultimate-hosts-blacklist-whitelist
  - wget -O "${TRAVIS_BUILD_DIR}/setup_recursor.sh"
    "${SCRIPT_SOURCE_URI}/recursor/setup_recursor.sh" &&
    sudo chmod +x "${TRAVIS_BUILD_DIR}/setup_recursor.sh"
  - sudo bash "${TRAVIS_BUILD_DIR}/setup_recursor.sh"

git:
  depth: 2

matrix:
  fast_finish: true

sudo: required

script:
  # We put both in same statement so that if one fails the whole test result will fail.
  #- echo "CPU's" && lscpu | grep -E '^Thread|^Core|^Socket|^CPU\('
  - sudo systemctl restart mariadb.service pdns-recursor.service
  #- sudo mysql -u root -h localhost -e "CREATE DATABASE pyfunceble DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
  #- sudo mysql -u root -h localhost -e "CREATE USER 'root'@'%' IDENTIFIED BY ''"
  #- sudo mysql -u root -h localhost -e "CREATE USER 'pyfunceble'@'localhost' IDENTIFIED BY 'pyfunceble';"
  #- sudo mysql -u root -h localhost -e "GRANT ALL PRIVILEGES ON pyfunceble.* TO 'pyfunceble'@'localhost';"
  #- sudo mysql --user=pyfunceble --password=pyfunceble pyfunceble < ${HOME}/db/pyfunceble.sql
  - bash scripts/test.sh && bash scripts/pyfunceble.sh && sudo mkdir -p ${HOME}/db/ && sudo mariadb-dump --host=name="${DB_HOST}" --user="${DB_USERNAME}" --password="${DB_PASSWORD}" --opt "${DB_NAME}" > ${HOME}/db/pyfunceble.sql
  #- bash scripts/test.sh && bash scripts/pyfunceble.sh && sudo mysqldump --user=pyfunceble --password=pyfunceble --opt pyfunceble > ${HOME}/db/pyfunceble.sql
