dist: bionic

language: python

python:
  #- "3.7"
  - "3.8.1"

cache:
  pip: true
  directories:
    - $HOME/db/
    - ${TRAVIS_BUILD_DIR}/scripts/output/

git:
  depth: 3

env:
  global:
    - GIT_NAME: Spirillen
    - GIT_EMAIL: "44526987+spirillen@users.noreply.github.com"
    - TRAVIS_REPO_SLUG: ${TRAVIS_REPO_SLUG} #dns-test/rpz.mypdns.cloud
    - TZ: UTC
    - PYFUNCEBLE_AUTO_CONFIGURATION: YES
    - ROOT_DIR: "${TRAVIS_BUILD_DIR}"
    - TEST_DIR: "${ROOT_DIR}/test_data"
    - SCRIPT_DIR: "${ROOT_DIR}/scripts"

addons:
  mariadb: '10.4'
  apt:
    packages:
      - dos2unix
      - msttcorefonts
      - lsof
      - pdns-recursor
    update: true
  
install:
  - pip3 install --upgrade pip
  - pip3 install pyfunceble==3.0.0
  #- pip3 install git+https://github.com/funilrys/PyFunceble.git@dev
  #- pip3 install ultimate-hosts-blacklist-whitelist

git:
  depth: 2

matrix:
  fast_finish: true

sudo: required

script:
  # We put both in same statement so that if one fails the whole test result will fail.
  #- echo "CPU's" && lscpu | grep -E '^Thread|^Core|^Socket|^CPU\('
  - sudo systemctl restart mysql.service pdns-recursor.service
  #- sudo mysql -u root -h localhost -e "CREATE DATABASE pyfunceble DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
  #- sudo mysql -u root -h localhost -e "CREATE USER 'root'@'%' IDENTIFIED BY ''"
  #- sudo mysql -u root -h localhost -e "CREATE USER 'pyfunceble'@'localhost' IDENTIFIED BY 'pyfunceble';"
  #- sudo mysql -u root -h localhost -e "GRANT ALL PRIVILEGES ON pyfunceble.* TO 'pyfunceble'@'localhost';"
  #- sudo mysql --user=pyfunceble --password=pyfunceble pyfunceble < ${HOME}/db/pyfunceble.sql
  - bash scripts/test.sh && bash scripts/pyfunceble.sh && sudo mkdir -p ${HOME}/db/ && sudo mysqldump --user=pyfunceble --password=pyfunceble --opt pyfunceble > ${HOME}/db/pyfunceble.sql
  #- bash scripts/test.sh && bash scripts/pyfunceble.sh && sudo mysqldump --user=pyfunceble --password=pyfunceble --opt pyfunceble > ${HOME}/db/pyfunceble.sql
