adblock: false
aggressive: false
auto_continue: true
ci: true
ci_autosave_commit: My Privacy DNS - AutoSave
ci_autosave_final_commit: My Privacy DNS - Results
ci_autosave_minutes: 5
ci_branch: "test-run"
ci_distribution_branch: master
command: ""
command_before_end: ""
cooldown_time: null
custom_ip: 0.0.0.0
days_between_db_retest: 1
days_between_inactive_db_clean: 180
db_type: json
debug: false
dns_lookup_over_tcp: false
dns_server:
    - 185.109.89.254
    - 130.225.244.166
    - 130.226.161.34
    - 185.38.24.52
    - 198.180.150.12
    - 94.126.178.9
    - 192.168.1.1
    - 91.239.100.100
    - 89.233.43.71
    - 198.180.150.12
    - 185.38.24.52
    - 130.226.161.34
    - 95.216.209.53
    - 116.203.32.67
    - 185.121.177.177
    - 169.239.202.202
    - 161.97.219.84
    - 104.168.144.17
    - 163.172.168.171
    - 94.103.153.176
    - 207.192.71.13
    - 178.63.116.152
    - 138.68.128.160
    - 188.226.146.136
    - 45.55.97.204
    - 79.124.7.81
filter: ""
generate_complements: false
generate_hosts: false
generate_json: false
header_printed: false
hierarchical_sorting: true
http_codes:
    active: true
    list:
        potentially_down:
            - 400
            - 402
            - 403
            - 404
            - 409
            - 410
            - 412
            - 414
            - 415
            - 416
        potentially_up:
            - 0
            - 300
            - 301
            - 302
            - 303
            - 304
            - 305
            - 307
            - 403
            - 405
            - 406
            - 407
            - 408
            - 411
            - 413
            - 417
            - 500
            - 501
            - 502
            - 503
            - 504
            - 505
        up:
            - 100
            - 101
            - 200
            - 201
            - 202
            - 203
            - 204
            - 205
            - 206
    not_found_default: XXX
iana_whois_server: whois.iana.org
idna_conversion: false
inactive_database: true
less: true
links:
    api_date_format: https://pyfunceble.funilrys.com/api/date-format
    api_no_referer: https://pyfunceble.funilrys.com/api/no-referer
    config: https://raw.githubusercontent.com/funilrys/PyFunceble/master/.PyFunceble_production.yaml
    dir_structure: https://raw.githubusercontent.com/funilrys/PyFunceble/master/dir_structure_production.json
    iana: https://raw.githubusercontent.com/PyFunceble/iana/master/iana-domains-db.json
    ipv4_reputation: https://reputation.alienvault.com/reputation.data
    psl: https://raw.githubusercontent.com/PyFunceble/public-suffix/master/public-suffix.json
    repo: https://github.com/funilrys/PyFunceble
    requirements: https://raw.githubusercontent.com/funilrys/PyFunceble/master/requirements.txt
    user_agents: https://raw.githubusercontent.com/PyFunceble/user_agents/master/user_agents.json
local: false
logs: true
maximal_processes: 25
mining: false
multiprocess: false
multiprocess_merging_mode: end
no_files: false
no_special: false
no_whois: false
outputs:
    analytic:
        directories:
            parent: Analytic
            potentially_down: POTENTIALLY_INACTIVE
            potentially_up: POTENTIALLY_ACTIVE
            suspicious: SUSPICIOUS
            up: ACTIVE
        filenames:
            potentially_down: down_or_potentially_down
            potentially_up: potentially_up
            suspicious: suspicious_and_merged_in_results
            up: active_and_merged_in_results
    complements:
        directory: complements
    default_files:
        dir_structure: dir_structure.json
        iana: iana-domains-db.json
        inactive_db: inactive_db.json
        mining: mining.json
        public_suffix: public-suffix.json
        results: results.txt
        whois_db: whois_db.json
    domains:
        directory: domains
        filename: list
    hosts:
        directory: hosts
        filename: hosts
        ip_filename: ips
    json:
        directory: json
        filename: dump.json
    logs:
        directories:
            parent: logs
            percentage: percentage
        filenames:
            auto_continue: continue.json
            date_format: date_format.json
            execution_time: execution_time.json
            no_referer: no_referer.json
            percentage: percentage.txt
            whois: whois.json
    parent_directory: output/
    splited:
        directory: splited
plain_list_domain: true
print_dots: true
quiet: true
reputation: false
rpz: false
shadow_file: false
share_logs: false
show_execution_time: true
show_percentage: true
simple: false
split: true
status:
    list:
        down:
            - down
            - inactive
            - error
        generic:
            - generic
        http_active:
            - http_active
        invalid:
            - ouch
            - invalid
        malicious:
            - malicious
            - bad_actor
        not_malicious: null
        potentially_down:
            - potentially_down
            - potentially_inactive
        potentially_up:
            - potentially_up
            - potentially_active
        sane:
            - sane
            - safe
        suspicious:
            - strange
            - suspicious
            - hum
        up:
            - up
            - active
        valid:
            - valid
            - syntax_valid
            - valid_syntax
    official:
        down: INACTIVE
        invalid: INVALID
        malicious: MALICIOUS
        sane: SANE
        up: ACTIVE
        valid: VALID
store_whois_record: false
syntax: false
timeout: 2
unified: false
use_reputation_data: false
user_agent:
    browser: firefox
    custom: null
    platform: linux
verify_ssl_certificate: false
whois_database: true
wildcard: false
