name: PyFunceble CI tests
on:
  schedule:
    - cron: '15 * * * *'
  push:
    branches:
      - 'master'
      - 'test-run'

env:
  PYFUNCEBLE_AUTO_CONFIGURATION: 'YES'
  GIT_NAME: '${{ secrets.GIT_BOT_NAME }}'
  GIT_EMAIL: '${{ secrets.GIT_BOT_EMAIL }}'
  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
  BUILD_NUMBER: '${{ github.run_number }}'
  PYFUNCEBLE_CONFIG_DIR: '${{ github.workspace }}/pyfunceble'
  PYFUNCEBLE_OUTPUT_LOCATION: '${{ github.workspace }}/'
  PYFUNCEBLE_DEBUG: True
  PYFUNCEBLE_DEBUG_LVL: DEBUG
  PYFUNCEBLE_DEBUG_ON_SCREEN: True
  PYFUNCEBLE_DB_CHARSET: '${{ secrets.MYPDNS_DB_CHAR }}'
  PYFUNCEBLE_DB_HOST: '${{ secrets.MYPDNS_DB_HOST }}'
  PYFUNCEBLE_DB_NAME: '${{ secrets.MYPDNS_DB_NAME }}'
  PYFUNCEBLE_DB_PASSWORD: '${{ secrets.MYPDNS_DB_PASS }}'
  PYFUNCEBLE_DB_PORT: '${{ secrets.MYPDNS_DB_PORT }}'
  PYFUNCEBLE_DB_USERNAME: '${{ secrets.MYPDNS_DB_USER }}'

jobs:
  test_and_push:
    name: Run PyFunceble against the files and push result to repository
    runs-on: '${{ matrix.os }}'

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - '3.9.1'
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Clone repository
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install requirements
        run: sudo bash "${{ github.workspace }}/scripts/requirements.sh"

      - name: Install PyFunceble
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir --pre PyFunceble-dev

      - name: Get PyFunceble version
        run: |
          PyFunceble --version

      - name: Create test source dir.
        run: mkdir -p "${{ github.workspace }}/no_git/"

      - name: Importing zone through AXFR
        run: |
          #drill axfr rpz.mypdns.cloud @axfr.ipv4.mypdns.cloud -p 5306 \
          #| tee > "${{ github.workspace }}/no_git/rpz.mypdns.cloud.list"
          drill axfr rpz.mypdns.cloud @axfr.ipv4.mypdns.cloud -p 5306 \
          > "${{ github.workspace }}/no_git/rpz.mypdns.cloud.list"

      # - name: zone testing workaround for #206
      #   run: |
      #     drill axfr rpz.mypdns.cloud @axfr.ipv4.mypdns.cloud -p 5306 \
      #     | grep -F "CNAME" | grep -vE "(^(\*\.|$))" \
      #     | sed 's/\.rpz\.mypdns\.cloud.*$//;s/^\s*\(.*[^ \t]\)\(\s\+\)*$/\1/' \
      #     | tee > "${{ github.workspace }}/no_git/rpz.mypdns.cloud.list"

      - name: Get head of test file
        run: |
          head -n 15 "${{ github.workspace }}/no_git/rpz.mypdns.cloud.list"

      - name: Run Domain tests # Workaround for https://github.com/funilrys/PyFunceble/issues/206
        run: |
          pyfunceble -ex --ci-max-minutes 45 \
          -f "${{ github.workspace }}/no_git/rpz.mypdns.cloud.list" \
